version: 1.0.{build}
image: Visual Studio 2015
platform:
- Win32
- x64
configuration:
- Release

before_build:
- ps: >-
    If ($env:APPVEYOR_BUILD_VERSION -Like "1.0*") {
      $version = Source/Script/SetGitProperties.cmd
      appveyor UpdateBuild -Version $version
    }
build:
  project: Project64.sln
  parallel: true
  verbosity: minimal
after_build:
- Source/Script/package_zip.cmd %APPVEYOR_BUILD_VERSION%-%platform%.zip %platform%

artifacts:
- path: Package/*.zip
